Gemspec/RequiredRubyVersion:
  Include:
    - 2.5
    - 2.6
    - 2.7

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 30
  Exclude:
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Max: 120

Security/YAMLLoad:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EachWithObject:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
