defaults:
  default_dwarf: "default dwarf"
  overriden_dwarf: "not yet overriden dwarf"
  erb_dwarf: "<%= ENV['ERB_DWARF'] %>"
  dwarf_password: :env
development:
  nil_dwarf: ~
  false_dwarf: false
  true_dwarf: true
  string_dwarf: "dwarf"
  overriden_dwarf: "already overriden dwarf"
  hash_dwarf:
    dwarf_1: "hello 1"
    dwarf_2: "hello 2"
test:
  nil_dwarf: ~
  false_dwarf: false
  true_dwarf: true
  string_dwarf: "dwarf"
  overriden_dwarf: "already overriden dwarf"
  hash_dwarf:
    dwarf_1: "hello 1"
    dwarf_2: "hello 2"
